### ISSUE TITLE
Scripts output are incomplete

### ISSUE THREAD

**Issue by addyosmani** [puppeteer/recorder#12]
When I record a set of actions and close Chromium, the Puppeteer Recorder script output is currently incomplete:

```js
const {open, click, type, submit} = require('./lib/runner.js');
open('https://chrome.com', {}, async () => {
  await click('aria/button[name="Ok, Got it"]');
  await click('aria/link[name="Go to Next Section"]');
```

What we are missing above are the following lines:

```diff
const {open, click, type, submit} = require('./lib/runner.js');
open('https://chrome.com', {}, async () => {
  await click('aria/button[name="Ok, Got it"]');
  await click('aria/link[name="Go to Next Section"]');
+});
```

which would avoid this error during replay:

```
SyntaxError: Unexpected end of input
    at wrapSafe (internal/modules/cjs/loader.js:1063:16)
    at Module._compile (internal/modules/cjs/loader.js:1111:27)
```

**Comment by jschfflr** [comment]
Can you verify that you closed Chromium (for example by pressing Cmd+Q on Mac)?
That should trigger the last line to be emitted.

**Comment by addyosmani** [comment]
Thanks. I re-tested and can reproduce this behavior by closing Chromium via UI (in this case I am doing it by hitting X):

![image](https://user-images.githubusercontent.com/110953/87197774-5d622580-c2af-11ea-996d-ac1090b89bf9.png)

If I exit out of the process via CLI the last line is also omitted:

![image](https://user-images.githubusercontent.com/110953/87198116-7c60b780-c2af-11ea-9e34-4a6e2845456e.png)

**Comment by jschfflr** [comment]
I updated the recorder to also finish the script when closing the tab that is being recorder or `Ctrl+C` is pressed on the console. Could check if it's now working as expected for you?

**Comment by addyosmani** [comment]
I believe this should be fixed now :)
