### ISSUE TITLE
Should navigations be made more explicit?

### ISSUE THREAD

**Issue by addyosmani** [puppeteer/recorder#14]
I attempted to use the Recorder to achieve the following:

1. Navigate to pptr.dev
2. Enter in a search term ("screenshot")
3. In the results page, click on the word "selector"
4. Be navigated to the MDN page for CSS selectors

The recorder was able to do great at steps 1-3. It was not able to capture that a navigation from the results page occurred in the script generated. This may make future debugging of scripts trickier.

Script:

```js
const {open, click, type, submit} = require('./lib/runner.js');
open('https://pptr.dev', {}, async () => {
  await click('aria/searchbox[name="start typing to search..."]');
  await type('aria/searchbox[name="start typing to search..."]', 'screenshot');
  await click('body > search-component > search-results > search-item.selected > search-item-title');
  await click('aria/link[name="selector"]');
});
```

![image](https://user-images.githubusercontent.com/110953/87080883-48b55d00-c1dd-11ea-8658-4633074bc26c.png)

If I redo the flow and once I get to MDN, continue interacting with the page, it appears to be able to replay events that happen on the MDN page. I was a little surprised here as in other Puppeteer recording projects, there are explicit URLs captured when navigations are performed, whilst Puppeteer's approach to using Aria selectors seems to make this less explicit. 

```js
const {open, click, type, submit} = require('./lib/runner.js');
open('https://pptr.dev', {}, async () => {
  await click('aria/searchbox[name="start typing to search..."]');
  await type('aria/searchbox[name="start typing to search..."]', 'screen');
  await click('body > search-component > search-results > search-item.selected');
  await click('body > content-component > pptr-api > content-box:nth-child(7) > api-method:nth-child(79) > ul > li:nth-child(1)');
  await click('aria/link[name="selector"]');
  await click('aria/button[name="Close banner"]');
  await click('aria/link[name="Universal selector"]');
});
```

I wonder if a good middle-ground here would be generating a comment when navigations to different URLs occur? (e.g `/* Navigated to https://.... */)

**Comment by jschfflr** [comment]
The output now includes expectations like:

```javascript
expect(page.url()).resolves.toBe('https://google.com');
```

to make these more explicit.
