### ISSUE TITLE
npx command in README points to other npm package

### ISSUE THREAD

**Issue by mathiasbynens** [puppeteer/recorder#16]

**Comment by jschfflr** [comment]
Which one? 
When running `npx puppeteer-recorder` on a device without the package linked, I get a `command not found: puppeteer-recorder`.

**Comment by mathiasbynens** [comment]
`npx puppeteer-recorder` points to https://www.npmjs.com/package/puppeteer-recorder which is a different package. (You get "command not found" because that package happens to not register a `bin` but that's not really relevant.)

**Comment by jschfflr** [comment]
WDYT about changing the name to `pptr-recorder` instead?
