### ISSUE TITLE
Add a way to slow down replay.

### ISSUE THREAD

**Issue by hashseed** [puppeteer/recorder#2]
Replay is pretty quick. It would be nice to have an option to artificially slow down steps, or linger at the last step a bit longer.

**Comment by hajonsoft** [comment]
How do we do a replay? Can we update the readme docs with how to run a recorded file?

As a developer I want to find an easy example to run the recorder with the correct options to store to a fire something like

npx @puppeteer/recorder http://mywebsite.com --output recording.js

to run the recording 
npmx @puppeteer/Whatever recording.js
