### ISSUE TITLE
Two chromium versions are downloaded

### ISSUE THREAD

**Issue by psmarshall** [puppeteer/recorder#22]
Starting from scratch:
```bash
$ git clone git@github.com:puppeteer/recorder.git
$ npm i                           # chromium r756035 is downloaded
$ npm run build
$ npx @pptr/recorder v8.dev       # chromium r782078 is downloaded
```

In total 2 chromiums are downloaded, is that intentional or is there a way to avoid it?

**Comment by psmarshall** [comment]
It seems to re-downloaded r782078 every time I run `npx @pptr/recorder v8.dev` as well.

**Comment by jschfflr** [comment]
We should update the README to include the new information about the download process
