### ISSUE TITLE
URL parameter requires scheme

### ISSUE THREAD

**Issue by hashseed** [puppeteer/recorder#3]
`npx puppeteer-recorder v8.dev` does not work, but `npx puppeteer-recorder http://v8.dev` does. Should we have a way to insert http:// automatically if it's not there?

**Comment by jschfflr** [comment]
That's a great idea. I'll add that.

**Comment by jschfflr** [comment]
Do you think it should default to `https:` or `http:`?

**Comment by hashseed** [comment]
https sgtm
